# Generated by Django 5.0.4 on 2024-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sclWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=50)),
                ('sName', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SchoolReg',
            },
        ),
    ]
